---
title: "COVID-CH project"
description: "Analyses of FOPH data - cases"
date: "`r Sys.datum()`"
author:
  - name: Radoslaw Panczak 
    url: https://github.com/RPanczak
    affiliation: ISPM
    affiliation_url: https://www.ispm.unibe.ch/
    orcid_id: 0000-0001-5141-683X
# bibliography: biblio.bib
output:
  distill::distill_article:
    highlight: pygments
    toc: true
    toc_depth: 1
    number_sections: true
editor_options: 
  chunk_output_type: console
---

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      # fig.width=8, fig.height=6, 
                      # out.width="800px", out.height="600px",
                      dpi=300)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)
set.seed(12345)

library(pacman) 
p_load(dplyr, tidyr, readr, scales, ggplot2,
       sjmisc, sjPlot,
       mgcv, gratia,
       gamlss)
```

<!-- ------------------------------------------------------------ --> 

# Raw data 

```{r}
cases <- read_rds("data/BAG-open/cases.rds") %>% 
  filter(geoRegion == "CH") %>% 
  mutate(Weekend = chron::is.weekend(datum)) 
```

## Daily & 7 day average

```{r echo=FALSE, layout="l-body-outset"}
cases %>% 
  ggplot(aes(x = datum)) + 
  geom_col(aes(y = entries), alpha = 5/10, linetype = 0) + 
  geom_line(aes(y = mean7d), color = "red") + 
  xlab("") + ylab("Cases") + theme_bw()
```

## Cumulative

```{r echo=FALSE, layout="l-body-outset"}
cases %>% 
  ggplot(aes(x = datum)) + 
  geom_col(aes(y = sumTotal), alpha = 5/10, linetype = 0) + 
  xlab("") + ylab("Cumulative cases") + theme_bw()
```

<!-- ------------------------------------------------------------ --> 

# Time adjusted GAM models of daily cases

```{r}
min_date <- as.numeric(min(cases$datum))

cases %<>% 
  # filter(Week > 4) %>% 
  arrange(datum) %>% 
  mutate(Day = as.numeric(datum) - min_date + 1)

cases %>% 
  ggplot(aes(entries)) +
  geom_histogram(binwidth = 10)

# sapply(cases, function(x) sum(is.na(x)))
```

```{r}
model_time_day_01 <- gam(entries ~  s(Day, bs = 'cs', k = 28), 
                         data = cases, 
                         family = scat(link = "identity"))

model_time_day_02 <- gam(entries ~  s(Day, bs = 'cs', k = 28) +
                           Weekend, 
                         data = cases, 
                         family = scat(link = "identity"))
```

```{r}
AIC(model_time_day_01, model_time_day_02)

summary(model_time_day_01)$sp.criterion
summary(model_time_day_02)$sp.criterion

summary(model_time_day_01)$r.sq
summary(model_time_day_02)$r.sq

anova(model_time_day_01, model_time_day_02, test="Chisq")
```

```{r, layout="l-body-outset"}
summary(model_time_day_02)
# gam.check(model_time_day_01)
# plot(model_time_day_01, pages=1)

draw(model_time_day_02)
appraise(model_time_day_02)
```

<!-- ------------------------------------------------------------ --> 

# Time adjusted GAMLSS models of daily cases

```{r}
data <- cases %>% 
  dplyr::select(entries, Day, Weekend)

model_time_day_01 <- gamlss(entries ~ pb(Day),
                            sigma.formula= ~ pb(Day),
                            data = data,
                            family = SHASHo())

plot(model_time_day_01)

model_time_day_02 <- gamlss(entries ~ pb(Day) + Weekend,
                            sigma.formula= ~ pb(Day),
                            data = data,
                            family = SHASHo())

plot(model_time_day_02)
```

