---
title: "COVID-CH project"
description: "Analyses of FOPH data - deaths"
date: "`r Sys.Date()`"
author:
  - name: Radoslaw Panczak 
    url: https://github.com/RPanczak
    affiliation: ISPM
    affiliation_url: https://www.ispm.unibe.ch/
    orcid_id: 0000-0001-5141-683X
# bibliography: biblio.bib
output:
  distill::distill_article:
    highlight: pygments
    toc: true
    toc_depth: 1
    number_sections: true
editor_options: 
  chunk_output_type: console
---

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      # fig.width=8, fig.height=6, 
                      # out.width="800px", out.height="600px",
                      dpi=300)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)
set.seed(12345)

library(pacman) 
p_load(dplyr, tidyr, readr, scales, ggplot2,
       sjmisc, sjPlot,
       mgcv, gratia)
```

<!-- ------------------------------------------------------------ --> 

# Raw data 

```{r}
deaths <- read_rds("data/BAG-open/deaths_cases.rds") %>% 
  filter(!is.na(pttoddat)) %>% 
  select(-fall_dt, -cases) %>% 
  arrange(pttoddat, canton, sex, age_group) %>% 
  mutate(weekend = chron::is.weekend(pttoddat))
```

```{r echo=FALSE, layout="l-body-outset"}
deaths %>% 
  group_by(pttoddat) %>% 
  summarise(deaths = sum(deaths)) %>% 
  mutate(deaths_7d = zoo::rollmean(deaths, k = 7, fill = NA)) %>% 
  ggplot(aes(x = pttoddat)) + 
  geom_col(aes(y = deaths), alpha = 5/10, linetype = 0) + 
  geom_line(aes(y = deaths_7d), color = "red") + 
  xlab("") + ylab("Deaths") + theme_bw()
```

```{r echo=FALSE, layout="l-body-outset"}
deaths %>% 
  group_by(pttoddat) %>% 
  summarise(deaths = sum(deaths)) %>% 
  mutate(cum_deaths = cumsum(deaths)) %>% 
  ggplot(aes(x = pttoddat)) + 
  geom_line(aes(y = cum_deaths), color = "red") + 
  xlab("") + ylab("Cumulative deaths") + theme_bw()
```

