---
title: "COVID-CH project"
description: "Meteo data - points"
date: "`r Sys.Date()`"
author:
  - name: Radoslaw Panczak 
    url: https://github.com/RPanczak
    affiliation: ISPM
    affiliation_url: https://www.ispm.unibe.ch/
    orcid_id: 0000-0001-5141-683X
# bibliography: biblio.bib
output:
  distill::distill_article:
    highlight: pygments
    toc: true
    toc_depth: 1
    number_sections: true
editor_options: 
  chunk_output_type: console
---

<!-- ------------------------------------------------------------ --> 
<!-- ------------------------------------------------------------ --> 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      # fig.width=8, fig.height=6, 
                      # out.width="800px", out.height="600px",
                      dpi=300)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(scipen=999)
set.seed(12345)

library(pacman) 
p_load(tidyverse, climate)
```

<!-- ------------------------------------------------------------ --> 

# Raw data 

## Weather stations available

```{r}
nearest_stations_ogimet(country = "Switzerland",
                        date = Sys.Date(),
                        add_map = TRUE,
                        point = c(8.2318, 46.7985),
                        no_of_stations = 200
)

ch_stations_ogimet <- nearest_stations_ogimet(country = "Switzerland",
                                              date = Sys.Date(),
                                              point = c(8.2318, 46.7985),
                                              no_of_stations = 200
) %>% 
  arrange(wmo_id)
```

## Stations with no data

```{r}
# example of correct call
bern <- meteo_ogimet(
  date = c(as.Date("2020-02-01"), Sys.Date() - 1),
  # date = c(Sys.Date() - 7, Sys.Date() - 1), 
  interval = "daily",
  coords = FALSE, 
  station = "06631")

# example of an error
error <- meteo_ogimet(
  date = c(as.Date("2020-02-01"), Sys.Date() - 1),
  # date = c(Sys.Date() - 7, Sys.Date() - 1), 
  interval = "daily",
  coords = FALSE, 
  station = "06647")

ch_stations_ogimet %>% 
  filter(wmo_id == "06647")

# removing errors
ch_stations_search <- ch_stations_ogimet %>% 
  filter(!wmo_id %in% c("06647", "06656", "06669", "06671", "06683",
                        "06687", "06728", "06730", "06789", "06799"))
```

## Data fetch and save

```{r eval=FALSE}
# https://masalmon.eu/2017/11/16/wheretoliveus/
ch_weather <- purrr::map_df(ch_stations_search$wmo_id, 
                         meteo_ogimet,
                         date = c(as.Date("2020-02-01"), Sys.Date() - 1),
                         # date = c(Sys.Date() - 7, Sys.Date() - 1), 
                         interval = "daily",
                         coords = FALSE)

write_rds(ch_weather, "data-raw/climate/ch_weather.Rds")
```

```{r}
ch_weather <- read_rds("data-raw/climate/ch_weather.Rds")
```

## Example - temps

```{r}
ggplot(ch_weather, aes(x = Date, y = TemperatureCAvg, group = station_ID)) + 
  geom_line(alpha = .1) +
  theme_minimal()
```

